package apps

// Turning the bundled Adminer DB UI on and off for a Laravel app.
//
// Adminer is a database client on a public hostname. It is genuinely useful
// while an app is being built and genuinely unwanted once it is live, so which
// of the two an app wants is a decision that changes over its life — not one to
// fix at create time and never revisit.
//
// There is no column for it. Whether an app has Adminer is already written in
// two places that have to agree for it to work at all: the `adminer` service in
// the compose file, and the service-domain row that routes a hostname to its
// port. A third copy in the apps table could only ever disagree with them, so
// the domain row is the answer to "is it on?" and this file is what keeps the
// compose file in step with it.
//
// The compose file is edited rather than re-rendered. A Laravel stack's file is
// generated by xdev, but the settings page also lets it be edited by hand, and
// re-rendering would silently discard those edits every time somebody toggled a
// checkbox. Removing and re-inserting one service leaves every other byte of
// the file exactly as it was.

import (
	"context"
	"errors"
	"fmt"
	"log"
	"strings"
	"time"

	"xdev/internal/runtime"
	"xdev/internal/store"
	"xdev/internal/templates"
)

// adminerService is the compose service name, in both the template partial and
// the file it renders into.
const adminerService = "adminer"

// CanToggleAdminer reports whether an app is one whose Adminer can be switched.
// Only Laravel: it is the only type that bundles Adminer, and the other type
// with a secondary UI (mail) needs its admin console to be administered at all.
func CanToggleAdminer(app store.App) bool {
	return app.Type == "laravel" && app.ComposePath != ""
}

// SetAdminer adds or removes the Adminer service and its hostname. It returns
// the hostname it published ("" when turning Adminer off), and is a no-op when
// the app is already in the requested state.
//
// The caller restarts the app: like every other compose edit, this one reaches
// the running stack only when the stack is recreated from the new file.
func (s *Service) SetAdminer(id int64, on bool) (string, error) {
	app, err := s.store.AppByID(id)
	if err != nil {
		return "", err
	}
	if !CanToggleAdminer(app) {
		return "", fmt.Errorf("%s apps do not bundle an Adminer to switch", app.Type)
	}
	proj, err := s.store.ProjectByID(app.ProjectID)
	if err != nil {
		return "", err
	}
	existing, err := s.store.AppServiceDomains(app.ID)
	if err != nil {
		return "", err
	}
	if (len(existing) > 0) == on {
		return "", nil // already there
	}
	hosts, err := s.store.AppHostnames(app.ID)
	if err != nil {
		return "", err
	}
	if len(hosts) == 0 {
		hosts = []string{app.Domain} // no domain rows yet: the app row is all there is
	}
	yaml, err := s.ReadCompose(app.ID)
	if err != nil {
		return "", err
	}
	if strings.TrimSpace(yaml) == "" {
		return "", errors.New("this app has no compose file to add a service to")
	}

	var svc []store.ServiceDomain
	if on {
		host := secondaryPrefix(app.Type) + "." + app.Domain
		if err := validHost(host); err != nil {
			return "", err
		}
		if owner := s.store.DomainOwner(host); owner != 0 && owner != app.ID {
			return "", fmt.Errorf("domain %q is already in use — free it, or rename this app's domain first", host)
		}
		ports, err := s.allocPorts(1, app.Port)
		if err != nil {
			return "", err
		}
		block, err := templates.RenderPartial(app.Type, "adminer_service", templates.Data{
			ProjectSlug: proj.Slug,
			AppSlug:     app.Slug,
			AppType:     app.Type,
			Env:         proj.Environment,
			AdminerPort: ports[0],
			SharedDB:    app.DBMode == store.DBShared,
		})
		if err != nil {
			return "", err
		}
		// Replacing rather than only inserting: a file that already carries an
		// `adminer` block (hand-added, or left behind by an interrupted toggle)
		// must not end up with two.
		yaml, _ = composeRemoveService(yaml, adminerService)
		if yaml, err = composeAddService(yaml, block); err != nil {
			return "", err
		}
		svc = []store.ServiceDomain{{Host: host, Port: ports[0]}}
	} else {
		// Take the container away before the file stops describing it: once the
		// service is gone from the compose file the engine no longer knows the
		// container belongs to this stack, and neither `down` nor `up` would
		// remove it. Best-effort — a stopped stack has nothing to remove, and a
		// leftover container is not a reason to refuse the setting.
		s.removeAdminerContainer(app)
		var found bool
		if yaml, found = composeRemoveService(yaml, adminerService); !found {
			log.Printf("app %d: no %q service in %s to remove", app.ID, adminerService, app.ComposePath)
		}
	}

	if err := writeComposeEdit(app.ComposePath, yaml); err != nil {
		return "", err
	}
	sslMode, isLocal := "internal", true
	if proj.Environment == "prod" {
		sslMode, isLocal = "letsencrypt", false
	}
	if err := s.store.ReplaceAppDomains(app.ID, hosts, svc, isLocal, sslMode); err != nil {
		return "", err
	}
	if len(svc) == 0 {
		return "", nil
	}
	return svc[0].Host, nil
}

// removeAdminerContainer stops and deletes just the adminer container, while the
// compose file still lists it.
func (s *Service) removeAdminerContainer(app store.App) {
	_, engine, workdir, pname, file, err := s.composeCtx(app.ID)
	if err != nil {
		return
	}
	ctx, cancel := context.WithTimeout(context.Background(), 60*time.Second)
	defer cancel()
	if out, err := runtime.Compose(ctx, engine, workdir, pname, file,
		"rm", "--stop", "--force", adminerService); err != nil {
		log.Printf("app %d: remove %s container: %v\n%s", app.ID, adminerService, err, out)
	}
}

// --- compose service surgery ------------------------------------------------
//
// Both functions work on lines rather than a parsed document on purpose. xdev
// has no YAML library, and round-tripping a compose file through one would
// rewrite the whole thing — comments, quoting, key order and all — to change one
// service. Line editing changes the lines it is asked to and leaves the rest
// byte for byte.

// composeRemoveService deletes a top-level service block and reports whether it
// found one. The block runs from the service's own key line to the next line at
// or above the indentation of that key (blank lines in between belong to it, so
// the blank line that separated it from what follows goes too).
func composeRemoveService(yaml, name string) (string, bool) {
	lines := strings.Split(yaml, "\n")
	start, indent, ok := findComposeService(lines, name)
	if !ok {
		return yaml, false
	}
	end := len(lines)
	for i := start + 1; i < len(lines); i++ {
		if isBlankOrComment(lines[i]) && lineIndent(lines[i]) > indent {
			continue
		}
		if strings.TrimSpace(lines[i]) == "" {
			continue
		}
		if lineIndent(lines[i]) <= indent {
			end = i
			break
		}
	}
	return strings.Join(append(lines[:start:start], lines[end:]...), "\n"), true
}

// composeAddService appends a rendered service block to the services section.
// The block is inserted at the end of that section but before any blank line
// trailing it, so the file keeps exactly one blank line between the last service
// and whatever follows.
func composeAddService(yaml, block string) (string, error) {
	lines := strings.Split(yaml, "\n")
	at, ok := composeServicesEnd(lines)
	if !ok {
		return "", errors.New("this compose file has no services: section to add to")
	}
	blockLines := strings.Split(strings.TrimSuffix(block, "\n"), "\n")
	out := make([]string, 0, len(lines)+len(blockLines))
	out = append(out, lines[:at]...)
	out = append(out, blockLines...)
	out = append(out, lines[at:]...)
	return strings.Join(out, "\n"), nil
}

// findComposeService returns the line index of a service's key inside the
// top-level services: mapping, and the indentation that marks a sibling.
func findComposeService(lines []string, name string) (int, int, bool) {
	inServices, indent := false, -1
	for i, raw := range lines {
		if strings.TrimSpace(raw) == "" || strings.HasPrefix(strings.TrimSpace(raw), "#") {
			continue
		}
		if lineIndent(raw) == 0 {
			inServices = strings.TrimSpace(raw) == "services:"
			indent = -1
			continue
		}
		if !inServices {
			continue
		}
		if indent < 0 {
			indent = lineIndent(raw)
		}
		if lineIndent(raw) == indent && strings.TrimSpace(raw) == name+":" {
			return i, indent, true
		}
	}
	return 0, 0, false
}

// composeServicesEnd returns the line index to insert a new service at: the end
// of the services section, before any blank lines that trail it.
func composeServicesEnd(lines []string) (int, bool) {
	inServices := false
	end := -1
	for i, raw := range lines {
		if strings.TrimSpace(raw) == "" {
			continue
		}
		if lineIndent(raw) == 0 && !strings.HasPrefix(strings.TrimSpace(raw), "#") {
			if inServices {
				end = i
				break
			}
			inServices = strings.TrimSpace(raw) == "services:"
			continue
		}
	}
	if !inServices {
		return 0, false
	}
	if end < 0 {
		end = len(lines)
	}
	// Back up over the blank lines, and over the comment block that introduces
	// the next section — those belong to what comes after services, not to the
	// last service in it.
	for end > 0 && isBlankOrComment(lines[end-1]) {
		end--
	}
	return end, true
}

func lineIndent(s string) int { return len(s) - len(strings.TrimLeft(s, " ")) }

func isBlankOrComment(s string) bool {
	t := strings.TrimSpace(s)
	return t == "" || strings.HasPrefix(t, "#")
}
